apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: project-api-quizz
  description: API to create Quizzes
  tags:
    - python
    - quizz
  annotations:
    github.com/project-slug: TigreDoMexico/project-api-quizz
spec:
  type: project-api
  lifecycle: production
  owner: TigreDoMexico
  definition: https://localhost:5000/swagger
